### ISSUE TITLE
Using only finalized blocks

### ISSUE THREAD

**Issue by gabrieljaegerde** [claudiazi/proposalAlertBot#1]
In the blockListener.ts I have had a bug until now. So you have to update this in your code too.
        
change the following row
https://github.com/claudiazi/proposalAlertBot/blob/ac249440a74e02b87e7f4b71d287469d008f0ead/src/network/blockListener.ts#L76

to

`const headSubscriber = this.apiPromise.rpc.chain.subscribeFinalizedHeads;`

**Comment by claudiazi** [comment]
updated! Thanks!!!
